optimize code
fcitx/fcitx5 pull request #1155
Opened 2024-10-12 09:08 UTC by hantengc

…other desktop environments in the future

2024-10-12 09:09 UTC, hantengc commented
@hantengc 这个pr

2024-10-18 01:59 UTC, wengxt requested changes

2024-10-18 01:59 UTC, wengxt commented on src/modules/notificationitem/notificationitem.cpp
> +    std::string customIconForDesktop() const {
since it's only about the keyboard icon, so just call it keyboardIconName or sth similar.

2024-10-22 08:12 UTC, hantengc commented on src/modules/notificationitem/notificationitem.cpp
> +    std::string customIconForDesktop() const {
> since it's only about the keyboard icon, so just call it keyboardIconName or sth similar.

好的，已修改~

2024-10-23 01:06 UTC, hantengc commented
修改改啦～

2024-10-23 01:06 UTC, hantengc commented
修改好了～

2025-01-14 01:19 UTC, merged