Fix #519
fcitx/fcitx5 pull request #520
Opened 2022-06-11 10:17 UTC by naokiri

Remove trailing slash from dir paths before checking uniqueness.

2022-06-18 20:20 UTC, wengxt requested changes
Please also add test case to this function.

2022-06-18 20:20 UTC, wengxt commented on src/lib/fcitx-utils/fs.cpp
> +    while (!cleanedPath.empty() && cleanedPath.back() == '/') {
This would be wrong if dirPath contains only slash.

2022-06-18 20:35 UTC, wengxt commented
Actually I believe there's no need to use cleanDirPath. cleanPath can already remove trailing slash.

2022-06-18 20:43 UTC, merged

2022-06-20 11:39 UTC, naokiri commented
You're right the cleanPath already did the job. Thanks for fixing!